[project]
name = "ai-platform-generic-worker"
version = "0.0.1"
description = "Configurable generic worker"
requires-python = ">=3.10"
dependencies = [
    "agent-framework>=1.0.0b1",
    "pydantic>=2.7",
    "python-dotenv>=1.0.1",
    "typer>=0.12.5"
]


